### ISSUE TITLE
why make it harder

### ISSUE THREAD

**Issue by adomagala1** [Bharat-Yadav-11/number-guessing-game#1]
Would not it be easier to simply create for each level the appropriate number of trials and then one petle and all the code write in 40 lines? here an example: 

`import random

def guessing_game():
    print("-------")
    print("Hello, Welcome To My Guessing Game")
    print("---")
    print("Please select the difficulty level:\n1. E - Easy\n2. M -  Medium\n3. H -  Hard")

    difficulty = input("What difficulty do you choose?\n").lower()  #

    if difficulty == "e":
        print("Easy difficulty selected")
        chances = 10
    elif difficulty == "m":
        print("Medium difficulty selected")
        chances = 5
    else:
        print("Hard difficulty selected")
        chances = 3

    target_number = random.randint(1, 100)
    print(f"You have {chances} chances to guess the number")

    is_correct(target_number, chances)

``

    while chances > 0:
        guess = int(input("Guess the number from 1 to 100: "))
        attempts += 1
        chances -= 1

        if guess < target_number:
            print("Your guess is too low")
        elif guess > target_number:
            print("Your guess is too high")
        else:
            print(f"You guessed it right in {attempts} attempts!")
            return

        print(f"Chances remaining: {chances}")

    print(f"Sorry, you've run out of chances. The correct number was {target_number}.")

guessing_game()
`

**Comment by Bharat-Yadav-11** [comment]
Yup! Bro, but I want to do it in **JavaScript**. You can use any of the programming language.

**Comment by adomagala1** [comment]
yea bro, I just saw those 150 lines of code in JavaScript and thought it was possible to do something shorter like in python. My bad. Have a great day my bro
